/** Exportador XLSX sin dependencias externas para Reportes Operacionales. */
const ExportService = {
  xml(v){return String(v??'').replace(/&/g,'&amp;').replace(/</g,'&lt;').replace(/>/g,'&gt;').replace(/"/g,'&quot;');},
  crc32(bytes){let crc=0xffffffff;for(const b of bytes){crc^=b;for(let i=0;i<8;i++)crc=(crc>>>1)^((crc&1)?0xedb88320:0);}return(crc^0xffffffff)>>>0;},
  zipStore(files){
    const enc=new TextEncoder(),u16=n=>new Uint8Array([n&255,(n>>>8)&255]),u32=n=>new Uint8Array([n&255,(n>>>8)&255,(n>>>16)&255,(n>>>24)&255]),join=parts=>{const out=new Uint8Array(parts.reduce((s,p)=>s+p.length,0));let o=0;parts.forEach(p=>{out.set(p,o);o+=p.length;});return out;};
    const locals=[],central=[];let offset=0;
    Object.entries(files).forEach(([path,content])=>{const name=enc.encode(path),data=content instanceof Uint8Array?content:enc.encode(content),crc=this.crc32(data),local=join([u32(0x04034b50),u16(20),u16(0),u16(0),u16(0),u16(0),u32(crc),u32(data.length),u32(data.length),u16(name.length),u16(0),name,data]);locals.push(local);central.push(join([u32(0x02014b50),u16(20),u16(20),u16(0),u16(0),u16(0),u16(0),u32(crc),u32(data.length),u32(data.length),u16(name.length),u16(0),u16(0),u16(0),u16(0),u32(0),u32(offset),name]));offset+=local.length;});
    const c=join(central),end=join([u32(0x06054b50),u16(0),u16(0),u16(central.length),u16(central.length),u32(c.length),u32(offset),u16(0)]);return join([...locals,c,end]);
  },
  columnaExcel(index){let n=index+1,s='';while(n){n--;s=String.fromCharCode(65+n%26)+s;n=Math.floor(n/26);}return s;},
  crearXlsx(nombreHoja,rows){
    const safe=String(nombreHoja||'Stock').replace(/[\\/?*\[\]:]/g,' ').slice(0,31)||'Stock';
    const sheetRows=rows.map((row,ri)=>`<row r="${ri+1}">${row.map((v,ci)=>{const ref=`${this.columnaExcel(ci)}${ri+1}`,num=ri>0&&typeof v==='number'&&Number.isFinite(v);return num?`<c r="${ref}"><v>${v}</v></c>`:`<c r="${ref}" t="inlineStr"><is><t xml:space="preserve">${this.xml(v)}</t></is></c>`;}).join('')}</row>`).join('');
    const files={
      '[Content_Types].xml':'<?xml version="1.0" encoding="UTF-8" standalone="yes"?><Types xmlns="http://schemas.openxmlformats.org/package/2006/content-types"><Default Extension="rels" ContentType="application/vnd.openxmlformats-package.relationships+xml"/><Default Extension="xml" ContentType="application/xml"/><Override PartName="/xl/workbook.xml" ContentType="application/vnd.openxmlformats-officedocument.spreadsheetml.sheet.main+xml"/><Override PartName="/xl/worksheets/sheet1.xml" ContentType="application/vnd.openxmlformats-officedocument.spreadsheetml.worksheet+xml"/></Types>',
      '_rels/.rels':'<?xml version="1.0" encoding="UTF-8" standalone="yes"?><Relationships xmlns="http://schemas.openxmlformats.org/package/2006/relationships"><Relationship Id="rId1" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/officeDocument" Target="xl/workbook.xml"/></Relationships>',
      'xl/workbook.xml':`<?xml version="1.0" encoding="UTF-8" standalone="yes"?><workbook xmlns="http://schemas.openxmlformats.org/spreadsheetml/2006/main" xmlns:r="http://schemas.openxmlformats.org/officeDocument/2006/relationships"><sheets><sheet name="${this.xml(safe)}" sheetId="1" r:id="rId1"/></sheets></workbook>`,
      'xl/_rels/workbook.xml.rels':'<?xml version="1.0" encoding="UTF-8" standalone="yes"?><Relationships xmlns="http://schemas.openxmlformats.org/package/2006/relationships"><Relationship Id="rId1" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/worksheet" Target="worksheets/sheet1.xml"/></Relationships>',
      'xl/worksheets/sheet1.xml':`<?xml version="1.0" encoding="UTF-8" standalone="yes"?><worksheet xmlns="http://schemas.openxmlformats.org/spreadsheetml/2006/main"><sheetViews><sheetView workbookViewId="0"><pane ySplit="1" topLeftCell="A2" activePane="bottomLeft" state="frozen"/></sheetView></sheetViews><sheetData>${sheetRows}</sheetData><autoFilter ref="A1:${this.columnaExcel(Math.max(0,(rows[0]?.length||1)-1))}${Math.max(1,rows.length)}"/></worksheet>`
    };
    return new Blob([this.zipStore(files)],{type:'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet'});
  },
  descargarXlsx(nombre,nombreHoja,rows){const url=URL.createObjectURL(this.crearXlsx(nombreHoja,rows)),a=document.createElement('a');a.href=url;a.download=nombre;document.body.appendChild(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(url),1000);},

  /** Libro OOXML con estilos, combinaciones y configuracion de impresion. */
  crearXlsxDocumento(doc){
    const safe=String(doc.nombreHoja||'Documento').replace(/[\\/?*\[\]:]/g,' ').slice(0,31)||'Documento';
    const styles={normal:0,title:1,subtitle:2,metaTitle:3,meta:4,header:5,origin:6,originOrganic:7,sku:8,skuOrganic:9,blocked:10,released:11,subtotal:12,grand:13,observation:14,signature:15,mapBand:16,mapEmpty:17,mapMuted:18,mapGreen:19,mapRed:20,mapAmber:21,mapPurple:22,mapGray:23,mapPink:24,mapOrange:25,mapCyan:26,mapBlue:27,mapWhite:28,mapFifo:29,mapGreenFifo:30,mapRedFifo:31,mapAmberFifo:32,mapPurpleFifo:33,mapGrayFifo:34,mapPinkFifo:35,mapOrangeFifo:36,mapCyanFifo:37,mapBlueFifo:38,mapWhiteFifo:39,mapBnSolid:40,mapBnDotted:41,mapBnDashed:42,mapBnDouble:43,mapBnMuted:44,mapBnFifo:45,mapAisle:46,mapTitle:47,mapMeta:48,packIndex:49,packLot:50,packArticle:51,packDescription:52,packKg:53,packBoxes:54,packDate:55,packInfo:56,packGeneral:57,packDm:58,packReserve:59,packHeaderLeft:60,mapSearched:61,mapSearchedFifo:62,mapBnSearched:63};
    const cellXml=(cell,ri,ci)=>{const c=(cell&&typeof cell==='object'&&!Array.isArray(cell))?cell:{v:cell};const ref=`${this.columnaExcel(ci)}${ri+1}`,sid=styles[c.s]??0,num=typeof c.v==='number'&&Number.isFinite(c.v);return num?`<c r="${ref}" s="${sid}"><v>${c.v}</v></c>`:`<c r="${ref}" s="${sid}" t="inlineStr"><is><t xml:space="preserve">${this.xml(c.v??'')}</t></is></c>`;};
    const rows=(doc.filas||[]).map((row,ri)=>`<row r="${ri+1}"${doc.altos?.[ri+1]?` ht="${doc.altos[ri+1]}" customHeight="1"`:''}>${row.map((c,ci)=>cellXml(c,ri,ci)).join('')}</row>`).join('');
    const cols=(doc.anchos||[]).map((w,i)=>`<col min="${i+1}" max="${i+1}" width="${w}" customWidth="1"/>`).join('');
    const merges=(doc.combinar||[]).map(r=>`<mergeCell ref="${r}"/>`).join('');
    const mergeXml=merges?`<mergeCells count="${doc.combinar.length}">${merges}</mergeCells>`:'';
    const freeze=doc.congelar?`<pane xSplit="${doc.congelar.x||0}" ySplit="${doc.congelar.y||0}" topLeftCell="${doc.congelar.celda||'A1'}" activePane="bottomRight" state="frozen"/>`:'';
    const margins={left:.25,right:.25,top:.35,bottom:.35,header:.1,footer:.1,...(doc.margenes||{})};
    const page=`<printOptions horizontalCentered="${doc.centrarHorizontal?1:0}"/><pageMargins left="${margins.left}" right="${margins.right}" top="${margins.top}" bottom="${margins.bottom}" header="${margins.header}" footer="${margins.footer}"/><pageSetup orientation="${doc.horizontal?'landscape':'portrait'}" paperSize="${doc.papelLegal?5:8}" pageOrder="overThenDown" fitToWidth="1" fitToHeight="${doc.ajustarAlto??0}"/>`;
    const baseStyles=[
      [0,0,0,0,'left'],[1,0,0,0,'left'],[2,0,0,0,'left'],[2,0,0,0,'left'],[0,2,1,0,'left'],[3,3,1,0,'center'],[3,4,0,0,'left'],[3,5,0,0,'left'],[6,6,0,0,'left'],[4,7,0,0,'left'],[5,8,1,0,'center'],[4,9,1,0,'center'],[6,2,1,0,'right'],[3,3,1,0,'right'],[5,10,2,0,'left'],[2,0,0,0,'center'],[3,3,1,0,'center'],[0,2,8,0,'center'],[0,2,8,0,'center'],[4,11,1,0,'center'],[3,12,1,0,'center'],[0,13,1,0,'center'],[3,14,1,0,'center'],[3,15,1,0,'center'],[3,16,1,0,'center'],[3,17,1,0,'center'],[3,18,1,0,'center'],[3,3,1,0,'center'],[0,0,1,0,'center'],[6,0,3,0,'center']
    ];
    const fifoStyles=[[4,11,3,0,'center'],[3,12,3,0,'center'],[0,13,3,0,'center'],[3,14,3,0,'center'],[3,15,3,0,'center'],[3,16,3,0,'center'],[3,17,3,0,'center'],[3,18,3,0,'center'],[3,3,3,0,'center'],[0,0,3,0,'center']];
    const monochromeStyles=[[0,0,4,0,'center'],[0,0,5,0,'center'],[0,0,6,0,'center'],[0,0,7,0,'center'],[2,2,8,0,'center'],[6,0,9,0,'center']];
    const packingStyles=[[7,0,1,0,'center'],[8,0,1,0,'left'],[9,0,1,0,'center'],[11,0,1,0,'left'],[8,0,1,0,'right',164],[12,0,1,0,'center'],[10,0,1,0,'center'],[10,0,1,0,'left'],[13,0,1,0,'left'],[12,0,1,0,'center'],[13,0,1,0,'center'],[3,3,1,0,'left']];
    const styleSpecs=[...baseStyles,...fifoStyles,...monochromeStyles,[3,4,3,0,'center'],[1,0,0,0,'center'],[2,0,0,0,'center'],...packingStyles,[3,18,3,0,'center'],[3,18,9,0,'center'],[0,0,9,0,'center']];
    const borders='<borders count="10"><border/><border><left style="thin"><color rgb="FFEDF2F7"/></left><right style="thin"><color rgb="FFEDF2F7"/></right><top style="thin"><color rgb="FFEDF2F7"/></top><bottom style="thin"><color rgb="FFEDF2F7"/></bottom></border><border><left style="medium"><color rgb="FFDD6B20"/></left><right style="thin"><color rgb="FFFEEBC8"/></right><top style="thin"><color rgb="FFFEEBC8"/></top><bottom style="thin"><color rgb="FFFEEBC8"/></bottom></border><border><left style="medium"><color rgb="FFF59E0B"/></left><right style="medium"><color rgb="FFF59E0B"/></right><top style="medium"><color rgb="FFF59E0B"/></top><bottom style="medium"><color rgb="FFF59E0B"/></bottom></border><border><left style="thin"><color rgb="FF111827"/></left><right style="thin"><color rgb="FF111827"/></right><top style="thin"><color rgb="FF111827"/></top><bottom style="thin"><color rgb="FF111827"/></bottom></border><border><left style="dotted"><color rgb="FF111827"/></left><right style="dotted"><color rgb="FF111827"/></right><top style="dotted"><color rgb="FF111827"/></top><bottom style="dotted"><color rgb="FF111827"/></bottom></border><border><left style="mediumDashed"><color rgb="FF111827"/></left><right style="mediumDashed"><color rgb="FF111827"/></right><top style="mediumDashed"><color rgb="FF111827"/></top><bottom style="mediumDashed"><color rgb="FF111827"/></bottom></border><border><left style="double"><color rgb="FF111827"/></left><right style="double"><color rgb="FF111827"/></right><top style="double"><color rgb="FF111827"/></top><bottom style="double"><color rgb="FF111827"/></bottom></border><border><left style="thin"><color rgb="FFCBD5E1"/></left><right style="thin"><color rgb="FFCBD5E1"/></right><top style="thin"><color rgb="FFCBD5E1"/></top><bottom style="thin"><color rgb="FFCBD5E1"/></bottom></border><border><left style="medium"><color rgb="FF111827"/></left><right style="medium"><color rgb="FF111827"/></right><top style="medium"><color rgb="FF111827"/></top><bottom style="medium"><color rgb="FF111827"/></bottom></border></borders>';
    const styleXml=`<?xml version="1.0" encoding="UTF-8" standalone="yes"?><styleSheet xmlns="http://schemas.openxmlformats.org/spreadsheetml/2006/main"><numFmts count="1"><numFmt numFmtId="164" formatCode="#\,##0.0"/></numFmts><fonts count="14"><font><sz val="8.5"/><name val="Segoe UI"/><color rgb="FF2D3748"/></font><font><b/><sz val="16"/><name val="Segoe UI"/><color rgb="FF2B6CB0"/></font><font><sz val="9"/><name val="Segoe UI"/><color rgb="FF718096"/></font><font><b/><sz val="8.5"/><name val="Segoe UI"/><color rgb="FFFFFFFF"/></font><font><b/><sz val="8.5"/><name val="Segoe UI"/><color rgb="FF22543D"/></font><font><b/><sz val="8.5"/><name val="Segoe UI"/><color rgb="FFC05621"/></font><font><b/><sz val="8.5"/><name val="Segoe UI"/><color rgb="FF1A365D"/></font><font><sz val="8.5"/><name val="Segoe UI"/><color rgb="FFA0AEC0"/></font><font><b/><sz val="8.5"/><name val="Consolas"/><color rgb="FF2B6CB0"/></font><font><b/><sz val="8.5"/><name val="Segoe UI"/><color rgb="FF4A5568"/></font><font><sz val="8.5"/><name val="Segoe UI"/><color rgb="FF4A5568"/></font><font><sz val="8.5"/><name val="Segoe UI"/><color rgb="FF2D3748"/></font><font><b/><sz val="8.5"/><name val="Segoe UI"/><color rgb="FF2D3748"/></font><font><sz val="8.5"/><name val="Segoe UI"/><color rgb="FF718096"/></font></fonts><fills count="19"><fill><patternFill patternType="none"/></fill><fill><patternFill patternType="gray125"/></fill>${['F7FAFC','2B6CB0','2D3748','276749','EBF8FF','F0FFF4','FEEBC8','C6F6D5','FFFAF0','10B981','EF4444','F59E0B','9333EA','64748B','EC4899','F97316','06B6D4'].map(x=>`<fill><patternFill patternType="solid"><fgColor rgb="FF${x}"/><bgColor indexed="64"/></patternFill></fill>`).join('')}</fills>${borders}<cellStyleXfs count="1"><xf numFmtId="0" fontId="0" fillId="0" borderId="0"/></cellStyleXfs><cellXfs count="${styleSpecs.length}">${styleSpecs.map(x=>`<xf numFmtId="${x[5]??0}" fontId="${x[0]}" fillId="${x[1]}" borderId="${x[2]}" xfId="0" applyAlignment="1"><alignment horizontal="${x[4]}" vertical="center" wrapText="1"/></xf>`).join('')}</cellXfs><cellStyles count="1"><cellStyle name="Normal" xfId="0" builtinId="0"/></cellStyles></styleSheet>`;
    const hasLogo=doc.logoBytes instanceof Uint8Array&&doc.logoBytes.length>0,drawing=hasLogo?'<drawing r:id="rId1"/>':'';
    const sheet=`<?xml version="1.0" encoding="UTF-8" standalone="yes"?><worksheet xmlns="http://schemas.openxmlformats.org/spreadsheetml/2006/main" xmlns:r="http://schemas.openxmlformats.org/officeDocument/2006/relationships"><sheetPr><pageSetUpPr fitToPage="1"/></sheetPr><sheetViews><sheetView workbookViewId="0" showGridLines="${doc.grilla===false?0:1}">${freeze}</sheetView></sheetViews><sheetFormatPr defaultRowHeight="15"/>${cols?`<cols>${cols}</cols>`:''}<sheetData>${rows}</sheetData>${mergeXml}${page}${drawing}</worksheet>`;
    const sheetRef=`'${safe.replace(/'/g,"''")}'`,absoluteRange=value=>String(value).replace(/([A-Z]+)(\d+)/g,(_m,col,row)=>`$${col}$${row}`);
    const definedNames=[doc.areaImpresion?`<definedName name="_xlnm.Print_Area" localSheetId="0">${sheetRef}!${absoluteRange(doc.areaImpresion)}</definedName>`:'',doc.repetirFilas?`<definedName name="_xlnm.Print_Titles" localSheetId="0">${sheetRef}!$${String(doc.repetirFilas).replace(':',':$')}</definedName>`:''].join('');
    const files={'[Content_Types].xml':`<?xml version="1.0" encoding="UTF-8" standalone="yes"?><Types xmlns="http://schemas.openxmlformats.org/package/2006/content-types"><Default Extension="rels" ContentType="application/vnd.openxmlformats-package.relationships+xml"/><Default Extension="xml" ContentType="application/xml"/>${hasLogo?'<Default Extension="png" ContentType="image/png"/><Override PartName="/xl/drawings/drawing1.xml" ContentType="application/vnd.openxmlformats-officedocument.drawing+xml"/>':''}<Override PartName="/xl/workbook.xml" ContentType="application/vnd.openxmlformats-officedocument.spreadsheetml.sheet.main+xml"/><Override PartName="/xl/worksheets/sheet1.xml" ContentType="application/vnd.openxmlformats-officedocument.spreadsheetml.worksheet+xml"/><Override PartName="/xl/styles.xml" ContentType="application/vnd.openxmlformats-officedocument.spreadsheetml.styles+xml"/></Types>`,'_rels/.rels':'<?xml version="1.0" encoding="UTF-8" standalone="yes"?><Relationships xmlns="http://schemas.openxmlformats.org/package/2006/relationships"><Relationship Id="rId1" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/officeDocument" Target="xl/workbook.xml"/></Relationships>','xl/workbook.xml':`<?xml version="1.0" encoding="UTF-8" standalone="yes"?><workbook xmlns="http://schemas.openxmlformats.org/spreadsheetml/2006/main" xmlns:r="http://schemas.openxmlformats.org/officeDocument/2006/relationships"><sheets><sheet name="${this.xml(safe)}" sheetId="1" r:id="rId1"/></sheets>${definedNames?`<definedNames>${definedNames}</definedNames>`:''}</workbook>`,'xl/_rels/workbook.xml.rels':'<?xml version="1.0" encoding="UTF-8" standalone="yes"?><Relationships xmlns="http://schemas.openxmlformats.org/package/2006/relationships"><Relationship Id="rId1" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/worksheet" Target="worksheets/sheet1.xml"/><Relationship Id="rId2" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/styles" Target="styles.xml"/></Relationships>','xl/styles.xml':styleXml,'xl/worksheets/sheet1.xml':sheet};
    if(hasLogo){files['xl/worksheets/_rels/sheet1.xml.rels']='<?xml version="1.0" encoding="UTF-8" standalone="yes"?><Relationships xmlns="http://schemas.openxmlformats.org/package/2006/relationships"><Relationship Id="rId1" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/drawing" Target="../drawings/drawing1.xml"/></Relationships>';files['xl/drawings/drawing1.xml']='<?xml version="1.0" encoding="UTF-8" standalone="yes"?><xdr:wsDr xmlns:xdr="http://schemas.openxmlformats.org/drawingml/2006/spreadsheetDrawing" xmlns:a="http://schemas.openxmlformats.org/drawingml/2006/main" xmlns:r="http://schemas.openxmlformats.org/officeDocument/2006/relationships"><xdr:oneCellAnchor><xdr:from><xdr:col>0</xdr:col><xdr:colOff>0</xdr:colOff><xdr:row>0</xdr:row><xdr:rowOff>0</xdr:rowOff></xdr:from><xdr:ext cx="1381125" cy="666750"/><xdr:pic><xdr:nvPicPr><xdr:cNvPr id="1" name="Logo Olmué"/><xdr:cNvPicPr/></xdr:nvPicPr><xdr:blipFill><a:blip r:embed="rId1"/><a:stretch><a:fillRect/></a:stretch></xdr:blipFill><xdr:spPr><a:prstGeom prst="rect"><a:avLst/></a:prstGeom></xdr:spPr></xdr:pic><xdr:clientData/></xdr:oneCellAnchor></xdr:wsDr>';files['xl/drawings/_rels/drawing1.xml.rels']='<?xml version="1.0" encoding="UTF-8" standalone="yes"?><Relationships xmlns="http://schemas.openxmlformats.org/package/2006/relationships"><Relationship Id="rId1" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/image" Target="../media/logo.png"/></Relationships>';files['xl/media/logo.png']=doc.logoBytes;}
    return new Blob([this.zipStore(files)],{type:'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet'});
  },
  descargarXlsxDocumento(nombre,doc){const url=URL.createObjectURL(this.crearXlsxDocumento(doc)),a=document.createElement('a');a.href=url;a.download=nombre;document.body.appendChild(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(url),1000);}
};
