/** Interfaz operacional táctil de alta visibilidad. */
const GrueroController = {
  root:null, action:null, pallet:null, codeContext:null, camera:'PROTER', band:0, renderer:null, clockTimer:null,
  hidBuffer:'', hidLastKeyAt:0, hidStartedAt:0,
  actions:{
    scan:['⌁','Escanear pallet','Identificá un pallet o caja'],assign:['↥','Ingresar a cámara','Asigná una posición disponible'],
    move:['⇄','Mover pallet','Cambiá su ubicación'],load:['▣','Enviar a carga','Derivá a Carga / Andén'],
    query:['⌕','Consultar pallet','Revisá su estado y ubicación'],bands:['▦','Ver bandas','Consultá pallets por banda'],
    undo:['↶','Devolver movimiento','Restaurá la ubicación anterior']
  },
  init(root){this.root=root;this.action=null;this.pallet=null;this.codeContext=null;this.camera='PROTER';this.band=0;this.render();this.bindConnectivity();this.bindHidScanner();},
  esc(value){const node=document.createElement('span');node.textContent=String(value??'');return node.innerHTML;},
  statusAbbr(p){return ABREVIATURAS_ESTADO_MAPA[p?.estado]||'—';},
  positionText(p){return p?.banda===null||p?.banda===undefined?'Sin posición activa':`${p.ubicacion} · Banda ${p.banda} · P${p.posicion} · ${p.altura}`;},
  render(){
    if(!this.root)return;const user=UserModel.getCurrentUser();
    const actions=Object.entries(this.actions).map(([key,item])=>`<button class="gruero-action ${this.action===key?'active':''}" data-action="${key}"><i>${item[0]}</i><strong>${item[1]}</strong><span>${item[2]}</span></button>`).join('');
    this.root.innerHTML=`<section class="gruero-view" aria-label="Operación Gruero"><header class="gruero-header"><div><span class="gruero-eyebrow">OPERACIÓN EN CÁMARA</span><h1>Estación Gruero</h1><p><i class="gruero-network"></i><b class="gruero-network-label"></b><em class="gruero-pending"></em></p><div class="gruero-status-strip" aria-live="polite"><span data-status="scanner">Lector listo</span><span data-status="network"></span><span data-status="sync"></span></div></div><div class="gruero-clock"><b id="grueroTime">--:--</b><span id="grueroDate">--</span></div><div class="gruero-operator"><i>${AppController.initials(user?.name)}</i><span><b>${this.esc(user?.name||'Operador')}</b><small>${this.esc(user?.role||'Gruero')}</small></span></div></header><div class="gruero-layout"><section class="gruero-main"><div class="gruero-actions" aria-label="Acciones operacionales">${actions}</div><section id="grueroWork" class="gruero-work panel-surface"></section></section><aside class="gruero-side"><h2>Flujo rápido</h2><ol><li class="${this.pallet?'done':''}">1. Identificar pallet</li><li class="${this.action?'done':''}">2. Elegir acción</li><li class="${this.action==='assign'||this.action==='move'?'done':''}">3. Seleccionar banda y posición</li><li>4. Confirmar</li></ol><button id="grueroSync" class="gruero-sync"><i></i>Sincronizar pendientes</button><div id="grueroSyncInfo" class="gruero-sync-info"></div></aside></div></section>`;
    this.root.querySelectorAll('.gruero-action').forEach(button=>button.onclick=()=>this.chooseAction(button.dataset.action));
    this.root.querySelector('#grueroSync').onclick=()=>this.sync();this.startClock();this.renderWork();this.updateConnectionUI();this.updatePending();
  },
  startClock(){clearInterval(this.clockTimer);const tick=()=>{const now=new Date(),time=this.root?.querySelector('#grueroTime'),date=this.root?.querySelector('#grueroDate');if(time)time.textContent=now.toLocaleTimeString('es-CL',{hour:'2-digit',minute:'2-digit'});if(date)date.textContent=now.toLocaleDateString('es-CL',{weekday:'short',day:'2-digit',month:'short'});};tick();this.clockTimer=setInterval(tick,1000);},
  bindConnectivity(){if(this._bound)return;this._bound=true;window.addEventListener('online',()=>{this.updateConnectionUI();this.sync();});window.addEventListener('offline',()=>this.updateConnectionUI());},
  bindHidScanner(){
    if(this._hidBound)return;this._hidBound=true;
    document.addEventListener('keydown',event=>{
      if(AppController.activeView!=='gruero'||event.ctrlKey||event.altKey||event.metaKey)return;
      if(event.target?.matches?.('input,textarea,select,[contenteditable="true"]'))return;
      const now=performance.now();
      if(event.key==='Enter'){
        const value=this.hidBuffer,elapsed=now-this.hidStartedAt;this.hidBuffer='';
        if(value.length>=3&&elapsed<=Math.max(700,value.length*70)){event.preventDefault();this.resolve(value,'LECTOR');}
        return;
      }
      if(event.key.length!==1)return;
      if(!this.hidBuffer||now-this.hidLastKeyAt>85){this.hidBuffer=event.key;this.hidStartedAt=now;}else this.hidBuffer+=event.key;
      this.hidLastKeyAt=now;clearTimeout(this._hidReset);this._hidReset=setTimeout(()=>{this.hidBuffer='';},500);
    });
  },
  updateConnectionUI(){const online=navigator.onLine,serverReady=Boolean(window.WmsSyncAdapter?.sendMovement),shellReady=/^https?:$/.test(location.protocol)&&'serviceWorker'in navigator;this.root?.querySelector('.gruero-network')?.classList.toggle('offline',!online);const label=this.root?.querySelector('.gruero-network-label');if(label)label.textContent=!online?'Sin conexión':serverReady?'En línea':'Modo local';const badge=this.root?.querySelector('[data-status="network"]');if(badge){badge.textContent=!shellReady?'Offline requiere servidor web':!online?'Modo offline':serverReady?'Servidor disponible':'Servidor no configurado';badge.classList.toggle('warning',!shellReady||!online||!serverReady);}},
  async updatePending(){const items=await GrueroSyncService.list(),status=GrueroSyncService.summary(items),n=this.root?.querySelector('.gruero-pending');if(n)n.textContent=items.length?`· ${status.pending} pendiente${status.pending===1?'':'s'}${status.conflicts?` · ${status.conflicts} conflicto${status.conflicts===1?'':'s'}`:''}`:'· Sin movimientos locales pendientes';const badge=this.root?.querySelector('[data-status="sync"]');if(badge){badge.textContent=items.length?`${status.pending} por sincronizar`:`${status.confirmed} confirmado${status.confirmed===1?'':'s'} por servidor`;badge.classList.toggle('warning',items.length>0);}},
  chooseAction(action){this.action=action;if(action==='undo')return this.returnPrevious();this.render();},
  renderWork(){const work=this.root?.querySelector('#grueroWork');if(!work)return;if(this.action==='bands')return this.renderBandViewer(work);if(!this.action||this.action==='scan'||this.action==='query')return this.renderScanner(work);if(!this.pallet)return this.renderScanner(work,`Primero identificá el pallet para ${this.actions[this.action][1].toLowerCase()}.`);if(this.action==='load')return this.renderLoad(work);this.renderDestination(work);},
  renderScanner(work,hint=''){
    work.innerHTML=`<header class="gruero-work-head"><div><span>IDENTIFICACIÓN</span><h2>${hint||'Escaneá o ingresá un pallet'}</h2><p>USB/Bluetooth, cámara e ingreso manual usan la misma validación operacional.</p></div></header>${this.pallet?this.palletCard():''}<form id="grueroScanForm" class="gruero-scan"><label for="grueroCode">Código de pallet, lote o caja</label><div><input id="grueroCode" autocomplete="off" autocapitalize="characters" spellcheck="false" inputmode="text" placeholder="Ej: A234" autofocus><button type="button" id="grueroCamera"><i></i>Cámara</button><button>Identificar</button></div><small id="grueroScanMessage" role="status">Lector listo · Enter confirma automáticamente</small></form>${this.pallet?'<div class="gruero-next-actions"><button data-next="assign">Ingresar a cámara</button><button data-next="move">Mover pallet</button><button data-next="load">Enviar a carga</button></div>':''}`;
    const form=work.querySelector('#grueroScanForm'),submit=()=>this.resolve(form.elements.grueroCode.value,'MANUAL');form.onsubmit=event=>{event.preventDefault();submit();};form.elements.grueroCode.onkeydown=event=>{if(event.key==='Enter'){event.preventDefault();submit();}};work.querySelector('#grueroCamera').onclick=()=>this.scanCamera();work.querySelectorAll('[data-next]').forEach(button=>button.onclick=()=>this.chooseAction(button.dataset.next));requestAnimationFrame(()=>form.elements.grueroCode?.focus());
  },
  palletCard(){const p=this.pallet,c=this.codeContext;return `<article class="gruero-pallet-card" style="--state:${COLORES_MAPA_ESTADO[p.estado]||'#64748B'}"><header><span>${this.esc(PalletModel.codigoVisualLegible(p))}</span><div><em>${c?.origenCodigo==='CAJA'?'Código de caja':c?.origenCodigo==='MANUAL'?'Ingreso manual':'Código de pallet'} · ${this.esc(c?.canalEntrada||'MANUAL')}</em><b>${this.esc(this.statusAbbr(p))}</b></div></header><strong>${this.esc(PalletModel.descripcion(p))}</strong><p>${this.esc(this.positionText(p))}</p><dl><div><dt>ID real de lote</dt><dd>${this.esc(PalletModel.idLoteReal(p))}</dd></div><div><dt>Artículo · pallet</dt><dd>${this.esc(p.articulo)} · ${this.esc(p.numero_pallet)}</dd></div><div><dt>Estado</dt><dd>${this.esc(p.estado)}</dd></div><div><dt>Cajas · kilos</dt><dd>${Number(p.cajas||0).toLocaleString('es-CL')} · ${PalletModel.kilos(p).toLocaleString('es-CL')} kg</dd></div></dl></article>`;},
  resolve(code,source='MANUAL'){const result=GrueroCodeResolver.resolverCodigo(code,source);if(!result.ok){this.pallet=null;this.codeContext=result;this.renderWork();const message=this.root?.querySelector('#grueroScanMessage');if(message){message.textContent=`⚠ ${result.error}`;message.className='error';}const badge=this.root?.querySelector('[data-status="scanner"]');if(badge){badge.textContent=result.ambiguity?'Código ambiguo':'Código no reconocido';badge.classList.add('error');}this.toast(result.error,result.ambiguity?'warning':'error');return;}this.pallet=result.pallet;this.codeContext=result;this.camera=this.pallet.ubicacion==='POST TUNEL'?'POST TUNEL':'PROTER';this.band=this.pallet.banda??(this.camera==='PROTER'?0:'01');this.render();this.toast(`✓ ${PalletModel.codigoVisualLegible(this.pallet)} identificado desde ${result.canalEntrada}`);},
  async scanCamera(){
    if(!navigator.mediaDevices?.getUserMedia)return this.message('Este navegador no permite abrir la cámara. Usá lector o ingreso manual.',true);
    let stream;
    try{
      stream=await CameraScannerService.abrirStream();
      console.info(`Camera stream: ${CameraScannerService.describir(stream)||'resolución no informada'}`);
      const native='BarcodeDetector'in window,overlay=document.createElement('div');overlay.className='gruero-camera-backdrop';overlay.innerHTML=`<section class="gruero-camera-dialog" role="dialog" aria-modal="true"><header><div><span>ESCÁNER DE CÁMARA</span><h2>Enfocá el código</h2></div><button type="button" aria-label="Cerrar cámara">×</button></header><div class="scan-stage"><video autoplay playsinline muted></video></div><div class="gruero-camera-fallback"><p>${native?'Lectura automática activa.':'Lectura automática no compatible en este navegador.'}</p><form><input autocomplete="off" placeholder="Ingresar código visible"><button>Resolver</button></form></div></section>`;
      document.getElementById('appRoot')?.appendChild(overlay);const video=overlay.querySelector('video');video.srcObject=stream;let timer=null,busy=false;
      const mejoras=CameraScannerService.potenciar(stream,overlay.querySelector('.scan-stage'));const close=()=>{if(timer)clearInterval(timer);mejoras.cerrar();stream?.getTracks().forEach(track=>track.stop());overlay.remove();};overlay.querySelector('header button').onclick=close;
      overlay.querySelector('form').onsubmit=event=>{event.preventDefault();const value=event.currentTarget.elements[0].value;if(!value)return;close();this.resolve(value,'CAMARA');};
      if(native){const detector=new BarcodeDetector({formats:['code_128','code_39','ean_13','ean_8','qr_code']});timer=setInterval(async()=>{if(busy||video.readyState<2)return;busy=true;try{const codes=await detector.detect(video);if(codes[0]?.rawValue){const value=codes[0].rawValue;close();this.resolve(value,'CAMARA');}}catch(_){}finally{busy=false;}},240);}
    }catch(_){stream?.getTracks().forEach(track=>track.stop());this.message('No fue posible abrir la cámara. Revisá permisos o usá lector/ingreso manual.',true);}
  },
  message(text,error=false){const message=this.root?.querySelector('#grueroScanMessage');if(message){message.textContent=`${error?'⚠':'✓'} ${text}`;message.className=error?'error':'';}},
  bands(){return this.camera==='PROTER'?Array.from({length:30},(_,i)=>i):['01','02',...Array.from({length:18},(_,i)=>i+1)];},
  cameraName(){return this.camera==='POST TUNEL'?'Cámara Post Túnel':'Cámara Proter';},
  bandLabel(band=this.band){return `${this.camera==='POST TUNEL'&&['01','02'].includes(String(band))?'Zona':'Banda'} ${band}`;},
  renderBandViewer(work){
    work.innerHTML=`<header class="gruero-work-head"><div><span>UBICACIÓN VIVA</span><h2>Ver banda · ${this.esc(this.cameraName())}</h2><p>Consulta los pallets y posiciones actuales. Este visor no asigna, mueve ni altera stock.</p></div></header><div class="gruero-destination gruero-band-viewer"><div class="gruero-camera-tabs"><button data-band-camera="PROTER" class="${this.camera==='PROTER'?'active':''}">Cámara Proter</button><button data-band-camera="POST TUNEL" class="${this.camera==='POST TUNEL'?'active':''}">Post Túnel</button></div><label>Banda a consultar<select id="grueroBandView">${this.bands().map(b=>`<option value="${b}" ${String(b)===String(this.band)?'selected':''}>${this.esc(this.bandLabel(b))}</option>`).join('')}</select></label><div id="grueroBandMap" class="gruero-band-map"></div><p class="gruero-map-help">Tocá un pallet para ver su información. C1 y C2 corresponden a los niveles reales.</p><aside id="grueroBandReadDetail" class="gruero-band-read-detail"><span>CONSULTA DE BANDA</span><b>Seleccioná un pallet</b><small>La visualización es solo lectura.</small></aside></div>`;
    work.querySelectorAll('[data-band-camera]').forEach(button=>button.onclick=()=>{this.camera=button.dataset.bandCamera;this.band=this.camera==='PROTER'?0:'01';this.renderWork();});
    work.querySelector('#grueroBandView').onchange=event=>{this.band=this.camera==='PROTER'?Number(event.target.value):event.target.value;this.renderWork();};
    this.renderBandViewerMap();
  },
  renderBandViewerMap(){
    const target=this.root?.querySelector('#grueroBandMap');if(!target)return;
    this.renderer=new MapaIsometricRenderer(target,{cameraMode:this.camera,data:MapaModel.getPallets(),onEmptyBand:()=>{},onSelect:pallet=>{if(!pallet)return;const detail=this.root?.querySelector('#grueroBandReadDetail');if(detail)detail.innerHTML=this.bandReadDetail(pallet);}});
    this.renderer.renderBand(this.band,MapaModel.getPallets());
  },
  bandReadDetail(pallet){return `<span>PALLET EN ${this.esc(this.bandLabel())}</span><b>${this.esc(PalletModel.codigoVisualLegible(pallet))}</b><small>${this.esc(PalletModel.descripcion(pallet))}</small><dl><div><dt>Artículo</dt><dd>${this.esc(pallet.articulo)}</dd></div><div><dt>Estado</dt><dd>${this.esc(pallet.estado)}</dd></div><div><dt>Cajas</dt><dd>${Number(pallet.cajas||0).toLocaleString('es-CL')}</dd></div><div><dt>Kilos</dt><dd>${PalletModel.kilos(pallet).toLocaleString('es-CL')} kg</dd></div><div class="wide"><dt>Ubicación</dt><dd>${this.esc(this.positionText(pallet))}</dd></div></dl>`;},
  renderDestination(work){const move=this.action==='move';work.innerHTML=`<header class="gruero-work-head"><div><span>${move?'MOVIMIENTO':'INGRESO A CÁMARA'}</span><h2>Elegí banda y tocá una posición libre</h2><p>${move?`Origen: ${this.esc(this.positionText(this.pallet))}`:'El pallet quedará ubicado en la posición elegida.'}</p></div></header>${this.palletCard()}<div class="gruero-destination"><div class="gruero-camera-tabs"><button data-camera="PROTER" class="${this.camera==='PROTER'?'active':''}">Cámara Proter</button><button data-camera="POST TUNEL" class="${this.camera==='POST TUNEL'?'active':''}">Post Túnel</button></div><label>Banda destino<select id="grueroBand">${this.bands().map(b=>`<option value="${b}" ${String(b)===String(this.band)?'selected':''}>${this.camera==='POST TUNEL'&&(b==='01'||b==='02')?'Zona':'Banda'} ${b}</option>`).join('')}</select></label><div id="grueroBandMap" class="gruero-band-map"></div><p class="gruero-map-help">Tocá una posición vacía. C1 y C2 corresponden a los niveles reales.</p></div>`;work.querySelectorAll('[data-camera]').forEach(button=>button.onclick=()=>{this.camera=button.dataset.camera;this.band=this.camera==='PROTER'?0:'01';this.renderWork();});work.querySelector('#grueroBand').onchange=event=>{this.band=this.camera==='PROTER'?Number(event.target.value):event.target.value;this.renderWork();};this.renderBand();},
  renderBand(){const target=this.root?.querySelector('#grueroBandMap');if(!target)return;this.renderer=new MapaIsometricRenderer(target,{cameraMode:this.camera,data:MapaModel.getPallets(),onEmptyBand:()=>{},onSelect:(pallet,slot)=>this.selectSlot(pallet,slot)});this.renderer.renderBand(this.band,MapaModel.getPallets());},
  async selectSlot(occupant,slot){if(occupant)return this.toast(`La posición P${slot.posicion} · ${slot.altura} está ocupada por ${PalletModel.codigoVisualLegible(occupant)}.`,'error');const result=MapaModel.moverPalletSeguro(this.pallet.id,this.camera,this.band,slot.posicion,slot.altura);if(!result.ok)return this.toast(result.error,'error');try{await this.record('move',result.anterior,{ubicacion:this.camera,banda:this.band,posicion:slot.posicion,altura:slot.altura});}catch(_){if(result.anterior.banda===null||result.anterior.banda===undefined)MapaModel.quitarDePosicion(this.pallet.id);else MapaModel.moverPalletSeguro(this.pallet.id,result.anterior.ubicacion,result.anterior.banda,result.anterior.posicion,result.anterior.altura);return this.toast('No fue posible guardar el movimiento localmente. No se aplicó el cambio.','error');}this.pallet=result.pallet;this.toast(`✓ ${PalletModel.codigoVisualLegible(this.pallet)} ubicado en banda ${this.band}, P${slot.posicion}, ${slot.altura}.`);this.action=null;this.render();},
  renderLoad(work){work.innerHTML=`<header class="gruero-work-head"><div><span>CARGA / ANDÉN</span><h2>Enviar pallet a carga</h2><p>Se quitará de su posición activa y continuará en el flujo existente.</p></div></header>${this.palletCard()}<div class="gruero-confirm"><p>El pallet conserva trazabilidad y posición anterior.</p><button id="grueroLoadConfirm">Enviar a carga</button><button id="grueroLoadCancel" class="secondary">Cancelar</button></div>`;work.querySelector('#grueroLoadConfirm').onclick=()=>this.sendLoad();work.querySelector('#grueroLoadCancel').onclick=()=>{this.action=null;this.render();};},
  async sendLoad(){const previous={ubicacion:this.pallet.ubicacion,banda:this.pallet.banda,posicion:this.pallet.posicion,altura:this.pallet.altura},result=MapaModel.agregarACarga(this.pallet.id);if(!result.ok)return this.toast(result.error,'error');try{await this.record('load',previous,null);}catch(_){MapaModel.quitarDeCarga(result.tab,this.pallet.id);return this.toast('No fue posible guardar el envío localmente. No se aplicó el cambio.','error');}this.toast(`✓ ${PalletModel.codigoVisualLegible(this.pallet)} enviado a carga.`);this.action=null;this.render();},
  async record(type,previous,destination){const user=UserModel.getCurrentUser(),item=await GrueroSyncService.enqueue({type,palletId:this.pallet.id,palletCode:PalletModel.codigoVisual(this.pallet),palletRealId:PalletModel.idLoteReal(this.pallet),previous,destination,userId:user?.id,userName:user?.name,deviceTime:new Date().toISOString()});this.lastMovement=item;await this.updatePending();if(navigator.onLine)this.sync();return item;},
  async returnPrevious(){if(!this.pallet)return this.render();const all=[...(await GrueroSyncService.list()),...GrueroSyncService.history()],items=all.filter(item=>item.palletId===this.pallet.id&&item.previous).sort((a,b)=>String(b.createdAt).localeCompare(String(a.createdAt))),last=items[0];if(!last)return this.toast('No hay una ubicación anterior registrada para este pallet.','error');const p=last.previous,target=MapaModel.buscarPalletEnPosicion(p.ubicacion,p.banda,p.posicion,p.altura);if(target&&target.id!==this.pallet.id)return this.toast('La ubicación anterior ya está ocupada. Elegí otra posición válida.','error');const current={ubicacion:this.pallet.ubicacion,banda:this.pallet.banda,posicion:this.pallet.posicion,altura:this.pallet.altura},result=MapaModel.moverPalletSeguro(this.pallet.id,p.ubicacion,p.banda,p.posicion,p.altura);if(!result.ok)return this.toast(result.error,'error');try{await this.record('return',current,p);}catch(_){MapaModel.moverPalletSeguro(this.pallet.id,current.ubicacion,current.banda,current.posicion,current.altura);return this.toast('No fue posible guardar la devolución localmente.','error');}this.pallet=result.pallet;this.toast('↶ Movimiento revertido a la ubicación anterior.');this.action=null;this.render();},
  async sync(){const result=await GrueroSyncService.sync(),info=this.root?.querySelector('#grueroSyncInfo');if(info)info.textContent=result.offline?`Sin conexión: ${result.pending} pendientes locales.`:result.unconfigured?`${result.pending} pendientes locales. Servidor aún no configurado.`:`${result.synced} confirmados · ${result.pending} pendientes · ${result.conflicts} conflictos.`;await this.updatePending();},
  toast(text,type=''){MapaController?.toast?.(text,type);}
};
